module.exports = [
  {
    title: "Love in Focus",
    img: "https://cdn.myanimelist.net/images/manga/1/196301.jpg",
    releaseYear: 2016,
    authors: "Yoko Nogiri",
    totalVolumes: 3,
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 3,
    review: "Basic romance manga with not much extra nuiance to it.",
    anime: false
  },
  {
    title: "Log Horizon",
    img: "https://cdn.myanimelist.net/images/manga/2/105755.jpg",
    releaseYear: 2010,
    authors: "Mamare Touno, Kazuhiro Hara, Koyuki",
    totalVolumes: 11,
    onGoing: false,
    ended: true,
    startedReading: false,
    finishedReading: false,
    rating: 0,
    review: "",
    anime: true
  },
  {
    title: "LivingStone",
    img: "https://cdn.myanimelist.net/images/manga/1/139875.jpg",
    releaseYear: 2009,
    authors: "Tomohiro Maekawa, Jinsei Kataoka",
    totalVolumes: 4,
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 8,
    review: "A very uniquie story that takles subjects like death and suicide in a very unique way.",
    anime: false
  },
  {
    title: "Levius",
    img: "https://cdn.myanimelist.net/images/manga/2/128213.jpg",
    releaseYear: 2012,
    authors: "Haruhisa Nakata",
    totalVolumes: 3,
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 4,
    review: "Interesting story with very beautiful imagry, lacks proper setup to get me invested",
    anime: false
  },
  {
    title: "If I could Reach You",
    img: "https://cdn.myanimelist.net/images/manga/3/196507.jpg",
    releaseYear: 2016,
    authors: "tMnR",
    totalVolumes: 7,
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 5,
    review: "A basic yuri, The MC is in love with someone who is already taken",
    anime: false
  },
  {
    title: "Hunter x Hunter",
    img: "https://cdn.myanimelist.net/images/manga/2/253119.jpg",
    releaseYear: 1998,
    authors: "Yoshihiro Togashi",
    totalVolumes: 36,
    onGoing: true,
    ended: false,
    startedReading: true,
    finishedReading: true,
    rating: 9,
    review: "A wonderful shounen that takes some very dark and unexpected turn. The story is simply wonderfully put togeather. The only downside being that it's been on break for more than 3 years",
    anime: true
  },
  {
    title: "How Do We Relationship?",
    img: "https://cdn.myanimelist.net/images/manga/1/221553.jpg",
    releaseYear: 2018,
    authors: "Tamifull",
    totalVolumes: 8,
    onGoing: true,
    ended: false,
    startedReading: true,
    finishedReading: false,
    rating: 7,
    review: "A nice yuri that doesn't shy away from any aspect of a relationship",
    anime: false
  },
  {
    title: "Haikyu!!",
    img: "https://cdn.myanimelist.net/images/manga/2/258225.jpg",
    releaseYear: 2012,
    authors: "Furudate Haruichi",
    totalVolumes: 45,
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: true,
    rating: 10,
    review: "A very wholesome experience. a story that has helped me through some very hard times.",
    anime: true
  },
  {
    title: "Go with the Clouds North by Northwest",
    img: "https://cdn.myanimelist.net/images/manga/1/201696.jpg",
    releaseYear: 2016,
    authors: "Irie Aki",
    totalVolumes: 5,
    onGoing: true,
    ended: false,
    startedReading: true,
    finishedReading: false,
    rating: 6,
    review: "A beautiful adventure story, but the mystery hasn't really gripped me.",
    anime: false
  },
  {
    title: "Goodnight Punpun",
    img: "https://cdn.myanimelist.net/images/manga/3/164420.jpg",
    releaseYear: 2007,
    authors: "Inio Asano",
    totalVolumes: 13,
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 0,
    review: "Deals with some very heavy real world subjects",
    anime: false
  }
]
