module.exports= [
  {
    title: "Love in Focus",
    img: "https://cdn.myanimelist.net/images/manga/1/196301.jpg",
    releaseYear: 2016,
    authors: "Yoko Nogiri",
    genre: ["Romance"],
    totalVolumes: 3,
    ownedVolumes: [1],
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 3,
    review: "Basic romance manga with not much extra nuiance to it.",
    anime: false
  },
  {
    title: "Log Horizon",
    img: "https://cdn.myanimelist.net/images/manga/2/105755.jpg",
    releaseYear: 2010,
    authors: "Mamare Touno, Kazuhiro Hara, Koyuki",
    genre: ["Action", "Adventure", "Fantasy", "Sci-Fi"],
    totalVolumes: 11,
    ownedVolumes: [1, 2],
    onGoing: false,
    ended: true,
    startedReading: false,
    finishedReading: false,
    rating: 0,
    review: "",
    anime: true
  },
  {
    title: "LivingStone",
    img: "https://cdn.myanimelist.net/images/manga/1/139875.jpg",
    releaseYear: 2009,
    authors: "Tomohiro Maekawa, Jinsei Kataoka",
    genre: ["Supernatural"],
    totalVolumes: 4,
    ownedVolumes: [1],
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 8,
    review: "A very uniquie story that takles subjects like death and suicide in a very unique way.",
    anime: false
  },
  {
    title: "Levius",
    img: "https://cdn.myanimelist.net/images/manga/2/128213.jpg",
    releaseYear: 2012,
    authors: "Haruhisa Nakata",
    genre: ["Sci-Fi"],
    totalVolumes: 3,
    ownedVolumes: [2],
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 4,
    review: "Interesting story with very beautiful imagry, lacks proper setup to get me invested",
    anime: false
  },
  {
    title: "If I could Reach You",
    img: "https://cdn.myanimelist.net/images/manga/3/196507.jpg",
    releaseYear: 2016,
    authors: "tMnR",
    genre: ["Drama", "Yuri"],
    totalVolumes: 7,
    ownedVolumes: [1],
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 5,
    review: "A basic yuri, The MC is in love with someone who is already taken",
    anime: false
  },
  {
    title: "Hunter x Hunter",
    img: "https://cdn.myanimelist.net/images/manga/2/253119.jpg",
    releaseYear: 1998,
    authors: "Yoshihiro Togashi",
    genre: ["Action", "Adventure", "Fantasy"],
    totalVolumes: 36,
    ownedVolumes: [1, 2],
    onGoing: true,
    ended: false,
    startedReading: true,
    finishedReading: true,
    rating: 9,
    review: "A wonderful shounen that takes some very dark and unexpected turn. The story is simply wonderfully put togeather. The only downside being that it's been on break for more than 3 years",
    anime: true
  },
  {
    title: "How Do We Relationship?",
    img: "https://cdn.myanimelist.net/images/manga/1/221553.jpg",
    releaseYear: 2018,
    authors: "Tamifull",
    genre: ["Drama", "Yuri"],
    totalVolumes: 8,
    ownedVolumes: [1, 2, 3, 4],
    onGoing: true,
    ended: false,
    startedReading: true,
    finishedReading: false,
    rating: 7,
    review: "A nice yuri that doesn't shy away from any aspect of a relationship",
    anime: false
  },
  {
    title: "Haikyu!!",
    img: "https://cdn.myanimelist.net/images/manga/2/258225.jpg",
    releaseYear: 2012,
    authors: "Furudate Haruichi",
    genre: ["Sports"],
    totalVolumes: 45,
    ownedVolumes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: true,
    rating: 10,
    review: "A very wholesome experience. a story that has helped me through some very hard times.",
    anime: true
  },
  {
    title: "Go with the Clouds North by Northwest",
    img: "https://cdn.myanimelist.net/images/manga/1/201696.jpg",
    releaseYear: 2016,
    authors: "Irie Aki",
    genre: ["Adventure", "Mystery", "Slice of life"],
    totalVolumes: 5,
    ownedVolumes: [1],
    onGoing: true,
    ended: false,
    startedReading: true,
    finishedReading: false,
    rating: 6,
    review: "A beautiful adventure story, but the mystery hasn't really gripped me.",
    anime: false
  },
  {
    title: "Goodnight Punpun",
    img: "https://cdn.myanimelist.net/images/manga/3/164420.jpg",
    releaseYear: 2007,
    authors: "Inio Asano",
    genre: ["Drama", "Slice of life"],
    totalVolumes: 13,
    ownedVolumes: [1],
    onGoing: false,
    ended: true,
    startedReading: true,
    finishedReading: false,
    rating: 0,
    review: "Deals with some very heavy real world subjects",
    anime: false
  }
]
